cafe/A/A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafe/A/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/', views.UserProfileView.as_view(), name='user_profile')
    ]

cafe/A/home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('menu/', views.MenuView.as_view(), name='menu'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

cafe/A/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }} mx-5">{{ msg }}</p>
    {% endfor %}
{% endif %}

cafe/A/templates/inc/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">

            <img class="mb-2"
                 src="{% static 'icons8-coffee-64.png' %}"
                 alt="icon cafe" class="img-fluid rounded-circle" style="width: 40px; height: 40px">
            Cafe Survivors</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% if request.user.is_authenticated %}
                    <a class="nav-link active" href="{% url 'orders:menu' %}">Menu</a>
                    <a class="nav-link active" href="{% url 'accounts:user_profile' %}">Profile</a>
                    <a class="nav-link active" href="{% url 'accounts:user_logout' %}">Log Out</a>
                {% else %}
                    <a class="nav-link active" href="{% url 'accounts:user_login' %}">Log In</a>
                    <a class="nav-link active" href="{% url 'accounts:user_register' %}">Sign Up</a>
                {% endif %}

            </div>
        </div>
    </div>
</nav>