cafe/A/A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafe/A/orders/urls.py
from django.urls import path, include
from . import views

app_name = 'orders'

# session_urls = [
#     path('set/', views.SetSessionView.as_view(), name='set'),
#     path('delete/', views.DelSessionView.as_view(), name='delete'),
#     path('down/', views.DownSessionView.as_view(), name='down'),
#     path('up/', views.UpSessionView.as_view(), name='up'),
#     path('table/', views.TableSessionView.as_view(), name='table'),
# ]

urlpatterns = [
    path('order', views.OrderView.as_view(), name='order'),
    path('menu/', views.MenuView.as_view(), name='menu'),
    # path('session/', include(session_urls), name='session'),
    path('set/', views.SetSessionView.as_view(), name='set'),
    path('delete/', views.DelSessionView.as_view(), name='delete'),
    path('down/', views.DownSessionView.as_view(), name='down'),
    path('up/', views.UpSessionView.as_view(), name='up'),
    path('table/', views.TableSessionView.as_view(), name='table'),
    path('request/', views.RequestView.as_view(), name='request'),
    path('verify/', views.VerifyView.as_view(), name='verify'),
]

cafe/A/orders/models.py
from django.db import models
from accounts.models import User


class MenuItem(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(max_length=100)
    price = models.IntegerField()
    category = models.CharField(max_length=20)
    image = models.ImageField(upload_to='products/%Y/%m/%d')
    discount = models.IntegerField()
    serving_time_period = models.TimeField()
    estimated_time = models.TimeField()


class Table(models.Model):
    table_number = models.PositiveIntegerField()
    cafe_space_position = models.PositiveIntegerField()
    use = models.BooleanField(default=False)


class Order(models.Model):
    tables = models.ForeignKey(Table, on_delete=models.CASCADE, related_name='torders')
    number = models.IntegerField()
    status = models.BooleanField()
    timestamp = models.DateTimeField(auto_now_add=True)
    users = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uorders')
    receipts = models.ForeignKey('Receipt', on_delete=models.CASCADE, related_name='rorders')
    menu_items = models.ForeignKey(MenuItem, on_delete=models.CASCADE, related_name='morders')


class Receipt(models.Model):
    total_price = models.IntegerField()
    final_price = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)
    users = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ureceipts')

cafe/A/orders/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import MenuItem, Order, Table, Receipt
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
import json
from suds.client import Client
import requests


class OrderView(LoginRequiredMixin, View):
    def get(self, request):
        total_price = 0
        total_price_without_discount = 0
        counter = 0
        orders = []
        receipt = Receipt.objects.first()
        table = request.session['table']
        table = Table.objects.filter(id=table).first()
        for k, v in request.session.items():
            item = MenuItem.objects.filter(slug=k).first()
            if item:
                counter += 1
                total_price += ((item.price * (100 - item.discount)) / 100) * int(v)
                total_price_without_discount += item.price * int(v)
                orders.append(
                    Order(tables=table, number=int(v), status=False, users=request.user, menu_items=item,
                          receipts=receipt))
        final_discount = total_price_without_discount - total_price
        request.session['total_price'] = total_price
        request.session['total_price_without_discount'] = total_price_without_discount
        for order in orders:
            print(order.menu_items.image.url)
        return render(request, 'orders/orders.html', {'orders': orders,
                                                      'total_price': total_price,
                                                      'counter': counter, 'table': table,
                                                      'final_discount': final_discount})


class MenuView(LoginRequiredMixin, View):
    def get(self, request):
        menu_items = MenuItem.objects.filter()
        tables = Table.objects.filter()
        list_of_category = list(set([item.category for item in menu_items]))

        req = request.session.items()
        items = []
        count = []
        for k, v in req:
            item = MenuItem.objects.filter(slug=k).first()
            if item:
                items.append(item)
                count.append(v)
        pack = zip(items, count)
        price = []
        for j in menu_items:
            price.append(j.price * (100 - j.discount) / 100)
        pack2 = zip(menu_items, price)
        return render(request, 'orders/menu.html',
                      {'tables': tables, 'menu_items': menu_items, 'list_of_category': list_of_category,
                       'pack': pack})


class SetSessionView(View):
    def post(self, request):
        res = json.load(request)

        for k, v in res.items():
            request.session[k.replace('_', ' ')] = v
        return HttpResponse({"error": ""}, status=400)


class DelSessionView(View):
    def post(self, request):
        res = list(request.POST.dict().keys())[0]
        del request.session[res.replace('_', ' ')]
        return HttpResponse({"error": ""}, status=400)


class DownSessionView(View):
    def post(self, request):
        response = list(request.POST.dict().keys())[0]
        request.session[response.replace('_', ' ')] = str(int(request.session[response.replace('_', ' ')]) - 1)
        return HttpResponse({"error": ""}, status=400)


class UpSessionView(View):
    def post(self, request):
        response = list(request.POST.dict().keys())[0]
        request.session[response.replace('_', ' ')] = str(int(request.session[response.replace('_', ' ')]) + 1)
        return HttpResponse({"error": ""}, status=400)


class TableSessionView(View):
    def post(self, request):
        print(request)
        print(request.session.items())
        try:
            return HttpResponse(request.session['table'])
        except Exception as e:
            messages.info(request, """You didn"t select a table. Please select one.""", 'info')
            return HttpResponse({"error": ""}, status=400)


# MMERCHANT_ID = '41b3a452-5a8c-4f34-86d8-84ba6e87413d'  # Required
MERCHANT = '41b3a452-5a8c-4f34-86d8-84ba6e87413d'  # Required
ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"
ZP_API_VERIFY = "https://api.zarinpal.com/pg/v4/payment/verify.json"
ZP_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/{authority}"
# amount = 11000  # Rial / Required
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
# email = 'email@example.com'  # Optional
# mobile = '09123456789'  # Optional
# Important: need to edit for realy server.
# to session ha 127.0.0.1:8000 ine inja ham ja localhost ino beza
CallbackURL = 'http://127.0.0.1:8000/orders/verify/'


class RequestView(View):
    def get(self, request):
        req_data = {
            "merchant_id": MERCHANT,
            "amount": int(request.session['total_price']),
            "callback_url": CallbackURL,
            "description": description,
            "metadata": {"mobile": request.user.phone_number, "email": request.user.email}
        }
        req_header = {"accept": "application/json", "content-type": "application/json'"}
        req = requests.post(url=ZP_API_REQUEST, data=json.dumps(
            req_data), headers=req_header)
        # code etebariye zarinpal
        authority = req.json()['data']['authority']
        if len(req.json()['errors']) == 0:
            return redirect(ZP_API_STARTPAY.format(authority=str(authority)))
        else:
            e_code = req.json()['errors']['code']
            e_message = req.json()['errors']['message']
            return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")


class VerifyView(View):
    def get(self, request):
        t_authority = request.GET['Authority']
        if request.GET.get('Status') == 'OK':
            req_header = {"accept": "application/json",
                          "content-type": "application/json'"}
            req_data = {
                "merchant_id": MERCHANT,
                "amount": int(request.session['total_price']),
                "authority": t_authority
            }
            req = requests.post(url=ZP_API_VERIFY, data=json.dumps(req_data), headers=req_header)
            if len(req.json()['errors']) == 0:
                t_status = req.json()['data']['code']
                if t_status == 100:
                    messages.info(request, """Payment was successful. Your order is being processed.""", 'success')

                    receipt = Receipt(total_price=request.session['total_price_without_discount'],
                                      final_price=request.session['total_price'],
                                      users=request.user)
                    req = request.session.items()
                    lst = []
                    table_id = request.session["table"]
                    tables = Table.objects.get(id=table_id)
                    tables.use = True
                    receipt.save()
                    tables.save()
                    for k, v in req:
                        item = MenuItem.objects.filter(slug=k).first()
                        if item:
                            order = Order(tables=tables, number=int(v), status=True, users=request.user,
                                          menu_items=item,
                                          receipts=receipt)
                            order.save()
                            lst.append(k)

                    # Clearing session memory
                    for i in lst:
                        del request.session[i]

                    del request.session['total_price']
                    del request.session['total_price_without_discount']

                    return redirect('accounts:user_profile')
                elif t_status == 101:
                    # tekrari
                    return HttpResponse('Transaction submitted : ' + str(
                        req.json()['data']['message']
                    ))
                else:
                    # na movafagh
                    return HttpResponse('Transaction failed.\nStatus: ' + str(
                        req.json()['data']['message']
                    ))
            else:
                e_code = req.json()['errors']['code']
                e_message = req.json()['errors']['message']
                return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")
        else:
            return HttpResponse('Transaction failed or canceled by user')

cafe/A/orders/templates/orders/menu.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<section class="px-5">
    <div class="container-fluid mt-5">
        <div class="row mb-5">
            <div class="col-lg-4 col-md-6">
                <div class="row mt-3 ms-0">
                    <div class="list-group" id="list-tab" role="tablist">
                        <a class="list-group-item list-group-item-action" id="list-drink-list"
                           data-bs-toggle="list" href="#list-Drink" role="tab" aria-controls="list-home">Drinks</a>
                        <a class="list-group-item list-group-item-action" id="list-cake-list" data-bs-toggle="list"
                           href="#list-Cake" role="tab" aria-controls="list-profile">Cakes</a>
                        <a class="list-group-item list-group-item-action" id="list-smoke-list" data-bs-toggle="list"
                           href="#list-Smoke" role="tab" aria-controls="list-profile">Smokes</a>

                    </div>
                </div>
                <div class="row h-100 justify-content-center ms-0">
                    <ul class="list-group mt-5 side_items">

                        {% for item,c in pack %}
                        <li id="{{ item.slug }}" class="list-group-item">
                            <div class="row d-flex justify-content-between align-items-center">
                                <div class="col-4">
                                    {{ item.slug }}
                                </div>

                                <div class="col-4 d-flex justify-content-center">
                                    <button id="down" class="btn btn-default"
                                            onclick="down('1','{{ item.slug }}')"><span
                                            class="glyphicon glyphicon-minus">-</span></button>
                                    <input type="text" id="{{ item.slug }}"
                                           class="form-control" value="{{ c }}" style="width: 85px"/>
                                    <button id="up" class="btn btn-default"
                                            onclick="up('20','{{ item.slug}}')"><span
                                            class="glyphicon glyphicon-plus">+</span></button>
                                </div>
                                <div class="col-4 d-flex justify-content-end">
                                    <button id="up" class="btn btn-danger ms-5"
                                            onclick="del('{{item.slug}}')"><span
                                            class="glyphicon glyphicon-plus">DEL</span></button>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <button
                                    class="btn btn-outline-dark me-2 mt-2"
                                    data-bs-toggle="modal"
                                    data-bs-target="#enroll"
                            >
                                Seat Selection
                            </button>
                        </li>


                    </ul>

                </div>
            </div>

            <div class="col-lg-8  col-md-6">
                <div class="tab-content" id="nav-tabContent">

                    {% for category in list_of_category %}
                    <div class="tab-pane fade show active" id="list-{{ category }}" role="tabpanel"
                         aria-labelledby="list-home-list">
                        <div class="row">
                            {% for menu_item in menu_items %}

                            {% if menu_item.category == category %}
                            <div class="col-lg-4 col-md-6 gy-3">
                                <div class="card">
                                    <img src={{ menu_item.image.url }}
                                         class="card-img-top img-fluid"
                                         alt="Fissure in Sandstone"/>
                                    <div class="card-body text-center">
                                        <h5 class="card-title">{{ menu_item.slug }}</h5>
                                        <h5 class="card-price"></h5>
                                        <span class="card-discount text-danger">{{ menu_item.discount }}%</span>
                                        <h6 class="line-through lead">
                                            <del> {{ menu_item.price}} T</del>
                                        </h6>

                                        <div class="d-grid gap-2">
                                            <button id="{{ menu_item.slug }}"
                                                    class="btn btn-outline-dark add_item me-2"
                                                    type="button">+
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>
    </div>
    </div>
</section>


<div class="modal fade" id="enroll" tabindex="-1" aria-labelledby="enrollLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="enrollLabel">Seat Selection</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                <p class="lead">Entrance Door</p>
                <form action="">
                    <div class="row">
                        {% for table in tables %}

                        <div class="col-4">
                            {% if table.use %}
                            <button type="button" id="table{{table.id}}" class="btn btn-danger table disabled">Table
                                {{table.id}}
                            </button>
                            {% else %}
                            <button type="button" id="table{{table.id}}" class="btn btn-secondary table">Table
                                {{table.id}}
                            </button>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>


                    <p class="lead">Cashier</p>
                </form>
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Close
                </button>
                <a type="button" id="make_order" onclick="make_order()" class="btn btn-primary">Make Order</a>

            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>

    $(document).ajaxSend(function (event, jqxhr, settings) {
    jqxhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
    });

    function make_order() {

        $.ajax({
            url: "{% url 'orders:table' %}",
            type: 'POST',
            success: function (data) {
                if (data == 'None') {
                    alert("You didn't select a table. Please select one to continue.")

                } else {
                    window.location.href = "{% url 'orders:order' %}"
                }

            }
        })
    }


    let myDict = {};
    document.addEventListener('DOMContentLoaded', () => {
        const drink = document.querySelector('#list-Drink')
        const cake = document.querySelector('#list-Cake')
        const smoke = document.querySelector('#list-Smoke')
        smoke.style.display = 'none';
        cake.style.display = 'none';


        document.querySelector('#list-drink-list').addEventListener('click', e => {
            e.preventDefault()
            cake.style.display = 'none';
            smoke.style.display = 'none';
            drink.style.display = 'block';
        })

        document.querySelector('#list-cake-list').addEventListener('click', e => {
            e.preventDefault()
            drink.style.display = 'none';
            smoke.style.display = 'none';
            cake.style.display = 'block';
        })

        document.querySelector('#list-smoke-list').addEventListener('click', e => {
            e.preventDefault()
            smoke.style.display = 'block';
            cake.style.display = 'none';
            drink.style.display = 'none';


        })

    })


    $('.table').on('click', function (e) {

        if (e.currentTarget.className.includes("click")) {

            $.ajax({
                url: "{% url 'orders:delete' %}",
                type: 'POST',
                data: 'table',
            })


            $(`#${
                    e.currentTarget.id
            }`).css('background-color', '#6C757D');
            $(`#${
                    e.currentTarget.id
            }`).removeClass('click');

        } else {
            let z = {}
            z["table"] = e.currentTarget.id.replace("table", '')
            $.ajax({
                url: "{% url 'orders:set' %}",
                type: 'POST',
                data: JSON.stringify(z),
                contentType: 'application/json'
            })

            $(`#${
                    e.currentTarget.id
            }`).css('background-color', '#07c941');

            $(`#${
                    e.currentTarget.id
            }`).addClass('click');
        }

    });


    $(".add_item").on('click', function (e) {
        let x = {}
        x[e.currentTarget.id] = '1'
        $.ajax({
            url: "{% url 'orders:set' %}",
            type: 'POST',
            data: JSON.stringify(x),
            contentType: 'application/json',
        })
        myDict[e.currentTarget.id] = 1;
        $(`#${e.currentTarget.id}`).addClass('disabled')
        $("ul").prepend(`<li id="${e.currentTarget.id}_li" class="list-group-item">
                                <div class="row d-flex justify-content-between align-items-center">
                                    <div class="col-4">

                                        ${e.currentTarget.id.replace('_', ' ')}
                                    </div>

                                    <div class="col-4 d-flex justify-content-center">
                                        <button id="down" class="btn btn-default" onclick="down('1','${e.currentTarget.id}_item')"><span class="glyphicon glyphicon-minus">-</span></button>
                                        <input type="text" id="${e.currentTarget.id}_item" class="form-control" value="1" style="width: 85px"/>
                                        <button id="up" class="btn btn-default" onclick="up('20','${e.currentTarget.id}_item')"><span class="glyphicon glyphicon-plus">+</span></button>
                                    </div>
                                    <div class="col-4 d-flex justify-content-end">
                                        <button id="up" class="btn btn-danger ms-5" onclick="del('${e.currentTarget.id}')"><span class="glyphicon glyphicon-plus">DEL</span></button>
                                    </div>
                                </div>

                            </li>`);
    });

    function up(max, item) {
        myDict[item.replace('_item', '')] = (myDict[item.replace('_item', '')] || 1) + 1
        document.getElementById(item).value = parseInt(document.getElementById(item).value) + 1;
        if (document.getElementById(item).value > parseInt(max)) {
            document.getElementById(item).value = max;
        } else {
            $.ajax({
                url: "{% url 'orders:up' %}",
                type: 'POST',
                data: item.replace('_item', ''),
            })
        }
    }

    function down(min, item) {
        myDict[item.replace('_item', '')] = (myDict[item.replace('_item', '')] || 1) - 1
        document.getElementById(item).value = parseInt(document.getElementById(item).value) - 1;
        if (document.getElementById(item).value < parseInt(min)) {
            document.getElementById(item).value = min;


        } else {
            $.ajax({
                url: "{% url 'orders:down' %}",
                type: 'POST',
                data: item.replace('_item', ''),
            })
        }
    }

    function del(item) {
        $.ajax({
            url: "{% url 'orders:delete' %}",
            type: 'POST',
            data: item,
        })
        $(`#${item}`).removeClass('disabled')
        $(`#${item}_li`).remove()
    }


    $(".list-group-item-action").on('click', function (e) {
        $(".list-group-item").removeClass('bg-dark border border-light')
        $(`#${e.currentTarget.id}`).addClass('bg-dark border border-light')


    })


</script>

{% endblock %}

cafe/A/orders/templates/orders/orders.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <style>
        @media (min-width: 1025px) {
            .h-custom {
                height: 100vh !important;
            }
        }

        .card-registration .select-input.form-control[readonly]:not([disabled]) {
            font-size: 1rem;
            line-height: 2.15;
            padding-left: .75em;
            padding-right: .75em;
        }

        .card-registration .select-arrow {
            top: 13px;
        }

        .bg-grey {
            background-color: #eae8e8;
        }

        @media (min-width: 992px) {
            .card-registration-2 .bg-grey {
                border-top-right-radius: 16px;
                border-bottom-right-radius: 16px;
            }
        }

        @media (max-width: 991px) {
            .card-registration-2 .bg-grey {
                border-bottom-left-radius: 16px;
                border-bottom-right-radius: 16px;
            }
        }
    </style>
    <section class="h-100 h-custom mt-5">
        <div class="container py-5 h-99">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12">
                    <div class="card card-registration card-registration-2" style="border-radius: 15px;">
                        <div class="card-body p-0">
                            <div class="row g-0">
                                <div class="col-lg-8">
                                    <div class="p-5">
                                        <div class="d-flex justify-content-between align-items-center mb-5">
                                            <h1 class="fw-bold mb-0 text-black">Shopping Cart</h1>
                                            <h6 class="mb-0 text-muted">{{ counter }} Items</h6>
                                        </div>
                                        <hr class="my-4">

                                        {% for order in orders %}
                                            <div class="row mb-4 d-flex justify-content-between align-items-center">
                                                <div class="col-md-2 col-lg-2 col-xl-2">
                                                    <img
                                                            src={{ order.menu_items.image.url }}
                                                            class="img-fluid rounded-3" alt="Cotton T-shirt">
                                                </div>
                                                <div class="col-md-3 col-lg-3 col-xl-3">
                                                    <h6 class="text-muted">{{ order.menuitem.name }}</h6>
                                                </div>
                                                <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                                                    <p class="mt-2">{{ order.number }}</p>

                                                </div>
                                                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                    <h6 class="mb-0">{{ order.menuitem.price }} T</h6>
                                                </div>

                                            </div>
                                            <hr class="my-4">
                                        {% endfor %}


                                        <div class="pt-5">
                                            <h6 class="mb-0"><a href="{% url 'orders:menu' %}"
                                                                class="btn btn-outline-dark">Back to menu</a></h6>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 bg-grey">
                                    <div class="p-5">
                                        <h3 class="fw-bold mb-5 mt-2 pt-1">Summary</h3>
                                        <div class="d-flex justify-content-between mb-5">
                                            <h5 class="text-uppercase">Total price</h5>
                                            <h5>{{ total_price }} T</h5>
                                        </div>
                                        <div class="d-flex justify-content-between mb-5">
                                            <h5 class="text-uppercase">Discount</h5>
                                            <h5 class="text-danger">{{ final_discount }} T</h5>
                                        </div>
                                        <hr class="my-4">
                                        <form class="mb-3">
                                            <div class="mb-3">
                                                <label for="exampleInputEmail1" class="form-label">Your Table</label>
                                                <h4>Table Number : {{ table.table_number }}</h4>
                                            </div>
                                            <a type="button" id="pay-button" href="{% url 'orders:request' %}"
                                               class="btn btn-dark btn-block btn-lg"
                                               data-mdb-ripple-color="dark">Pay
                                            </a>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}